// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruckProject.API.Context;

namespace TruckProject.API.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210909140308_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TruckProject.API.Models.ModelTruck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Model")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ModelTrucks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e86812a3-9d40-49de-bd13-6e4c3fc38445"),
                            Model = "FC"
                        },
                        new
                        {
                            Id = new Guid("0389f142-9e57-4225-8657-036e815d0e83"),
                            Model = "FH"
                        },
                        new
                        {
                            Id = new Guid("9c128ed3-7617-44e3-8bea-3d79a9d9e8f3"),
                            Model = "FM"
                        });
                });

            modelBuilder.Entity("TruckProject.API.Models.Truck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Chassi")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("FabricationYear")
                        .HasColumnType("int");

                    b.Property<Guid>("ModelTruckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelTruckId");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("TruckProject.API.Models.Truck", b =>
                {
                    b.HasOne("TruckProject.API.Models.ModelTruck", "ModelTruck")
                        .WithMany("Trucks")
                        .HasForeignKey("ModelTruckId")
                        .IsRequired();

                    b.Navigation("ModelTruck");
                });

            modelBuilder.Entity("TruckProject.API.Models.ModelTruck", b =>
                {
                    b.Navigation("Trucks");
                });
#pragma warning restore 612, 618
        }
    }
}
